// Generated by CoffeeScript 1.6.3
(function() {
  var file_data, submit_files, to_read,
    __hasProp = {}.hasOwnProperty;

  file_data = {};

  to_read = 0;

  Object.size = function(obj) {
    var k, size;
    size = 0;
    for (k in obj) {
      if (!__hasProp.call(obj, k)) continue;
      size++;
    }
    return size;
  };

  $(".upload-file").each(function() {
    return this.addEventListener("change", function(e) {
      var file, reader,
        _this = this;
      e.stopPropagation();
      e.preventDefault();
      if (e.target.files.length === 1) {
        file = e.target.files[0];
        if (file.type !== "image/png") {
          alert("Error: " + this.id + " isn't a PNG!");
          throw new Error;
        }
        reader = new FileReader;
        reader.onload = function(e) {
          file_data[_this.id] = e.target.result;
          to_read--;
          return console.log("Loaded " + _this.id);
        };
        to_read++;
        return reader.readAsDataURL(file);
      } else {
        console.error("Error handling " + this.id);
        return delete file_data[this.id];
      }
    });
  });

  submit_files = function() {
    if (to_read !== 0) {
      console.log("Not all read, delaying…");
      setTimeout(submit_files, 200);
      return;
    }
    if (Object.size(file_data === 0)) {
      return alert("You must add one or more files");
    }
    return chrome.storage.local.set({
      sid: "test",
      files: file_data
    }, function() {
      return alert("Your mod is now installed!");
    });
  };

  $("#submit").click(submit_files);

}).call(this);
