// Generated by CoffeeScript 1.6.3
(function() {
  chrome.storage.local.get("files", function(vals) {
    var fileTypes, files, script, type, _i, _len;
    files = vals.files;
    fileTypes = ["tiles", "splats", "flair", "speedpad", "speedpadred", "speedpadblue", "portal"];
    for (_i = 0, _len = fileTypes.length; _i < _len; _i++) {
      type = fileTypes[_i];
      if (type in files) {
        document.getElementById(type).src = files[type];
      }
    }
    script = document.createElement("script");
    script.textContent = "console.log(\"Hi from inside!\");\n(function () {\n	(function () {\n		console.log(\"Hi\")\n		try {\n			tagpro.api.redrawBackground()\n		} catch (e) {\n			console.log(\"Try again...\")\n			setTimeout(arguments.caller.callee, 100)\n		}\n	})()\n})()";
    document.head.appendChild(script);
    return script.parentNode.removeChild(script);
  });

}).call(this);
