// Generated by CoffeeScript 1.6.3
(function() {
  var tpmmServer;

  tpmmServer = "http://tagpro-mod-manager.herokuapp.com";

  qwest.get("" + tpmmServer + "/mods").success(function() {
    var loader, mods, ul;
    mods = this.response;
    loader = document.getElementById("loader");
    ul = document.getElementById("mods");
    return chrome.storage.local.get("sid", function(vals) {
      var author, author_text, div, img, li, mod, sid, title, title_text, _i, _len, _results;
      loader.style.display = "none";
      sid = vals.sid;
      _results = [];
      for (_i = 0, _len = mods.length; _i < _len; _i++) {
        mod = mods[_i];
        li = document.createElement("li");
        li.dataset.modid = mod._id !== "5292f07824c79b0b50000001" ? mod._id : "vanilla";
        if (sid === li.dataset.modid) {
          li.className = "mod sidmatch";
        } else {
          li.className = "mod";
        }
        ul.appendChild(li);
        div = document.createElement("div");
        div.className = "modinfo";
        title = document.createElement("div");
        title.className = "modtitle";
        div.appendChild(title);
        title_text = document.createTextNode(mod.name);
        title.appendChild(title_text);
        author = document.createElement("div");
        author.className = "modauthor";
        div.appendChild(author);
        author_text = document.createTextNode("By " + mod.author);
        author.appendChild(author_text);
        li.appendChild(div);
        img = document.createElement("img");
        img.src = mod.thumbnail;
        li.appendChild(img);
        _results.push(li.addEventListener("click", function() {
          var _this = this;
          loader.style.display = "block";
          return qwest.get("" + tpmmServer + "/files/" + this.dataset.modid).success(function(data) {
            return chrome.storage.local.set({
              sid: _this.dataset.modid,
              files: data.files
            }, function() {
              var ele, _j, _len1, _ref;
              _ref = document.getElementsByClassName("sidmatch");
              for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
                ele = _ref[_j];
                ele.className = "mod";
              }
              _this.className = "mod sidmatch";
              loader.style.display = "none";
              return alert("Mod installed!");
            });
          });
        }));
      }
      return _results;
    });
  });

}).call(this);
